apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: webapp-deployment
spec:
  selector:
    matchLabels:
      app: webapp
  replicas: 2 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: webappcontainer
          image: venky12345/webapp:latest # Image that will be used to containers in the cluster
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8040 # The port that the container is running on in the cluster
